--1
SELECT *
FROM LGDEPARTMENT

--2
SELECT PROD_SKU, PROD_DESCRIPT, PROD_TYPE, PROD_BASE, PROD_CATEGORY, PROD_PRICE
FROM LGPRODUCT
WHERE PROD_BASE = 'WATER' AND PROD_CATEGORY = 'SEALER'

--3
SELECT EMP_FNAME, EMP_LNAME, EMP_EMAIL, EMP_HIREDATE
FROM LGEMPLOYEE
WHERE EMP_HIREDATE >= '2001-01-01' AND EMP_HIREDATE <= '2010-12-31'

--4
SELECT EMP_FNAME, EMP_LNAME, EMP_PHONE, EMP_TITLE, DEPT_NUM
FROM LGEMPLOYEE
WHERE EMP_TITLE = 'CLERK I' OR DEPT_NUM = 300

--5
SELECT EMP_NUM, EMP_FNAME, EMP_LNAME
FROM LGEMPLOYEE
WHERE EMP_NUM = 83731 OR EMP_NUM = 83745 OR EMP_NUM = 84039
	(
		SELECT EMP_NUM, SAL_FROM, SAL_END
		FROM LGSALARY_HISTORY
		WHERE EMP_NUM IN (83731, 83745, 84039)
	)
ORDER BY EMP_NUM, SAL_FROM

--6
SELECT C.CUST_FNAME, C.CUST_LNAME, C.CUST_STREET, C.CUST_CITY, C.CUST_STATE, C.CUST_ZIP, C.CUST_CODE
FROM LGCUSTOMER C INNER JOIN LGINVOICE I ON C.CUST_CODE = I.CUST_CODE
				  INNER JOIN LGPRODUCT P ON 
WHERE BRAND_NAME = 'FORESTERS BEST' AND INV_DATE BETWEEN '2013-07-15' AND '2013-07-31'

--7
SELECT EMP_NUM, EMP_LNAME, EMP_EMAIL, EMP_TITLE
FROM LGEMPLOYEE
WHERE EMP_TITLE LIKE '%ASSOCIATE'

--8
SELECT BRAND_NAME,
	COUNT(BRAND_NAME) AS BRAND_STOCK
FROM LGPRODUCT, LGBRAND
GROUP BY BRAND_NAME

--9
SELECT PROD_TYPE,
	COUNT(PROD_TYPE) AS TYPE_STOCK
FROM LGPRODUCT
WHERE PROD_BASE = 'WATER'
GROUP BY PROD_TYPE

--10
SELECT PROD_TYPE, PROD_BASE,
	COUNT(PROD_TYPE) AS TYPE_STOCK
FROM LGPRODUCT
GROUP BY PROD_TYPE, PROD_BASE

--11
SELECT BRAND_ID,
	COUNT(PROD_TYPE) AS BRAND_STOCK
FROM LGPRODUCT
GROUP BY BRAND_ID

--12
SELECT B.BRAND_ID, B.BRAND_NAME, cast(AVG(P.PROD_PRICE)as decimal(10,2)) as AVERAGE_PRICE
FROM LGBRAND B INNER JOIN LGPRODUCT P ON  B.BRAND_ID = P.BRAND_ID
GROUP BY B.BRAND_NAME, B.BRAND_ID

--13
SELECT D.DEPT_NUM, E.EMP_HIREDATE
FROM LGDEPARTMENT D INNER JOIN LGEMPLOYEE E ON E.EMP_NUM = D.EMP_NUM
GROUP BY D.DEPT_NUM, E.EMP_HIREDATE
HAVING E.EMP_HIREDATE = MIN(EMP_HIREDATE)

--14
SELECT	E.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME, MAX(S.SAL_AMOUNT)
FROM	LGEMPLOYEE E INNER JOIN LGSALARY_HISTORY S ON E.EMP_NUM = S.EMP_NUM
WHERE	DEPT_NUM = 200				
GROUP BY E.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME
	
--15
SELECT C.CUST_CODE, C.CUST_FNAME, C.CUST_LNAME, SUM(I.INV_TOTAL) AS TOTALS
FROM LGCUSTOMER C INNER JOIN LGINVOICE I ON C.CUST_CODE = I.CUST_CODE
GROUP BY C.CUST_CODE, C.CUST_FNAME, C.CUST_LNAME, I.INV_TOTAL
HAVING SUM(I.INV_TOTAL) > 1500
--I BELIEVE MY PROBLEM HERE IS I'M NOT TOTALING THE INV_TOTAL COLUMN, BUT I'M UNSURE 
--WHAT I'VE DONE INCORRECTLY. QET

--16
SELECT D.DEPT_NUM, D.DEPT_NAME, D.DEPT_PHONE, D.EMP_NUM, E.EMP_LNAME
FROM LGDEPARTMENT D INNER JOIN LGEMPLOYEE E ON D.EMP_NUM = E.EMP_NUM
ORDER BY E.EMP_LNAME

--17
SELECT V.VEND_ID, V.VEND_NAME, B.BRAND_NAME
FROM LGVENDOR V INNER JOIN LGBRAND B ON V.VEND_NAME = B.VEND_NAME

--18
SELECT E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, SUM(I.INV_TOTAL) AS INVOICE_TOTAL
FROM LGEMPLOYEE E INNER JOIN LGINVOICE I ON E.EMP_NUM = I.EMPLOYEE_ID
GROUP BY E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME
ORDER BY E.EMP_LNAME, E.EMP_FNAME

--19
CREATE VIEW AVG_PROD_PRICE AS 
SELECT BRAND_NAME, AVG(PROD_PRICE) AS AVG_PRICE
FROM	LGPRODUCT P INNER JOIN LGBRAND B ON P.BRAND_ID = B.BRAND_ID
GROUP BY PROD_PRICE

SELECT	BRAND_NAME, PROD_PRICE
FROM	AVG_PROD_PRICE
WHERE	AVG_PRICE = 
		(SELECT	MAX(AVG_PRICE)
		 FROM	AVG_PROD_PRICE	

--20

--21
SELECT  D.DEPT_NAME, D.DEPT_PHONE, E.EMP_TITLE
FROM	LGDEPARTMENT D INNER JOIN LGEMPLOYEE E ON D.EMP_NUM = E.EMP_NUM
WHERE	D.DEPT_NAME IN (SELECT	CUST_FNAME 
						FROM	LGCUSTOMER
						WHERE	CUST_LNAME IN (SELECT INV_DATE, INV_TOTAL
											  FROM	LGINVOICE
											  WHERE INV_DATE = '05-08-2011'
											)
						)
		AND
		E.EMP_TITLE IN (SELECT	EMP_TITLE
						   FROM		LGEMPLOYEE
						   WHERE	EMP_TITLE LIKE 'MANAGER'
						  )	





















		



